name: shopping_cart
description: "A modern Flutter shopping app demo."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.0+3
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/app_icon.png"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
  macos:
    generate: true
    image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
